#!/bin/bash

yarn build && \
node dist/src/index.js --extensions ".ts" > output.txt && \
convert -size 680x3000 xc:white -font "FreeMono" -pointsize 6 -fill black \
-annotate +6+6 "@output.txt" unclean-output.png  && \
convert unclean-output.png -resize 1000x3000! output.png && \
rm unclean-output.png output.txt && \
echo "Generated patterns to output.png"
